### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by fogeater** [nviennot/android-checkin#1]
use the command
java -jar android-checkin-1.0.har email passwd

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
    at com.android.checkin.Main.main(Main.java:17)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 1 more

Java version 1.7.0_60-ea

**Comment by saubcy** [comment]
you should set the classpath, just like this :
java -cp lib/commons-codec-1.6.jar;lib/commons-logging-1.1.1.jar;lib/fluent-hc-4.2.2.jar;lib/httpclient-4.2.2.jar;lib/httpclient-cache-4.2.2.jar;lib/httpcore-4.2.2.jar;lib/httpmime-4.2.2.jar;lib/protobuf-java-2.4.1.jar;android-checkin-1.0.jar com.android.checkin.Main <mail> <passwd>

**Comment by petRUShka** [comment]
You should use : instead of ; . Like this:

java -cp lib/commons-codec-1.6.jar:lib/commons-logging-1.1.1.jar:lib/fluent-hc-4.2.2.jar:lib/httpclient-4.2.2.jar:lib/httpclient-cache-4.2.2.jar:lib/httpcore-4.2.2.jar:lib/httpmime-4.2.2.jar:lib/protobuf-java-2.4.1.jar:android-checkin-1.0.jar com.android.checkin.Main
