### ISSUE TITLE
Cannot generate Android ID

### ISSUE THREAD

**Issue by sorcer1122** [nviennot/android-checkin#12]
Hello,

I am getting the following error:

Fetching auth (google service)...
Error=UNKNOWN_ERR
java.io.IOException: Can't find Auth // HTTP/1.1 404 Not Found
	at com.android.checkin.Checkin.postFormFetchValue(Checkin.java:108)
	at com.android.checkin.Checkin.fetchAuthGsf(Checkin.java:77)
	at com.android.checkin.Checkin.checkin(Checkin.java:54)
	at com.android.checkin.Main.main(Main.java:17)

Any ideas how to fix it?

**Comment by sorcer1122** [comment]
Fixed, thanks a lot for the quick help
