### ISSUE TITLE
Error=BadAuthentication

### ISSUE THREAD

**Issue by stefanjauker** [nviennot/android-checkin#13]
Hi,

I often get a BadAuthentication error message. When i execute the command in a loop it shows 3 of 10 times the following error:

```shell
java -cp 'android-checkin-1.0.jar:lib/*' com.android.checkin.Main $MAIL $PASSWORD
Fetching auth (google service)...
Error=BadAuthentication
java.io.IOException: Can't find Auth // HTTP/1.1 403 Forbidden
	at com.android.checkin.Checkin.postFormFetchValue(Checkin.java:108)
	at com.android.checkin.Checkin.fetchAuthGsf(Checkin.java:77)
	at com.android.checkin.Checkin.checkin(Checkin.java:54)
	at com.android.checkin.Main.main(Main.java:17)
```

any idea?

**Comment by iliis** [comment]
Same here. I *always* get a 403 error. And yes, the credentials are valid ;)

**Comment by kkhanmohammadi** [comment]
Hi, Did you guys find the solution? I have the same issue.

**Comment by kkhanmohammadi** [comment]
I got the same error, did you guys found a solution?

**Comment by iliis** [comment]
No, at least not a direct one. I'm now using MicroG (http://microg.org/) with Yalp Store (https://github.com/yeriomin/YalpStore), so I don't need a Google account at all anymore ;)

**Comment by kkhanmohammadi** [comment]
Thansks @iliis ! I will try that.
