### ISSUE TITLE
Error: To access your account, you must sign in on the web.

### ISSUE THREAD

**Issue by petRUShka** [nviennot/android-checkin#3]
When I try to create android ID, I get following error:

```
$ java -cp lib/commons-codec-1.6.jar:lib/commons-logging-1.1.1.jar:lib/fluent-hc-4.2.2.jar:lib/httpclient-4.2.2.jar:lib/httpclient-cache-4.2.2.jar:lib/httpcore-4.2.2.jar:lib/httpmime-4.2.2.jar:lib/protobuf-java-2.4.1.jar:android-checkin-1.0.jar com.android.checkin.Main  user@gmail.com PassWord
Fetching auth (google service)...
Error=NeedsBrowser
Url=https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Fandroid%2Fauth%3Fhl%3Den%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbuuRNhxg9OYiPoF9ZCz5wHc8dG6NxCXkaK_GpU-DboZuedeRPaZ7M-qLJRv6lJcir0yolsUeqYW4xrux2_
ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.
java.io.IOException: Can't find Auth // HTTP/1.1 403 Forbidden
        at com.android.checkin.Checkin.postFormFetchValue(Checkin.java:108)
        at com.android.checkin.Checkin.fetchAuthGsf(Checkin.java:77)
        at com.android.checkin.Checkin.checkin(Checkin.java:54)
        at com.android.checkin.Main.main(Main.java:17)
```

**Comment by DamienCassou** [comment]
I confirm the error message. When clicking on the Url in the error, I'm arriving at a google page indefinitely saying "One moment please..."

**Comment by petRUShka** [comment]
@DamienCassou, same behaviour on click.

**Comment by pailey** [comment]
go here: https://www.google.com/settings/security/lesssecureapps
and turn on

**Comment by DamienCassou** [comment]
Thanks

**Comment by DamienCassou** [comment]
I have the impression that https://accounts.google.com/b/0/DisplayUnlockCaptcha is also necessary

**Comment by petRUShka** [comment]
It seems that lesssecureapps is enough.

**Comment by calebj** [comment]
I use two-factor authentication, and had to make an [application-specific password](https://security.google.com/settings/security/apppasswords). I don't think the URL that it vomits up can do anything for android-checkin.
