### ISSUE TITLE
Apache error

### ISSUE THREAD

**Issue by ghost** [nviennot/android-checkin#8]
I've used this before, but now it seems to fail. I've tried on 3 different computers, but they all give the same error: 

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpEntity`
`at com.android.checkin.Main.main(Main.java:17)`
`Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity`
`at java.net.URLClassLoader.findClass(URLClassLoader.java:381)`
`at java.lang.ClassLoader.loadClass(ClassLoader.java:424)`
`at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)`
`at java.lang.ClassLoader.loadClass(ClassLoader.java:357)`
`... 1 more`

**Comment by youxiafuture** [comment]
@Zekario try to  add lib directory like this: java -Djava.ext.dirs=./lib ...
