### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by matlink** [nviennot/android-checkin#9]
Seems to be a certificate error somewhere (and I can't build the project again, too many errors) : 

```
$ java -Djava.ext.dirs=./lib -jar android-checkin-1.0.jar "a" "a"
Fetching auth (google service)...
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
    at org.apache.http.impl.client.AbstractHttpClient.xecute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
    at com.android.checkin.Checkin.postFormFetchValue(Checkin.java:88)
    at com.android.checkin.Checkin.fetchAuthGsf(Checkin.java:77)
    at com.android.checkin.Checkin.checkin(Checkin.java:54)
    at com.android.checkin.Main.main(Main.java:17)`
```

**Comment by repsorp** [comment]
same here
what to do then ?
